version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./:/var/www
    networks:
      - app-network
    restart: always

  web:
    image: nginx:alpine
    container_name: web
    working_dir: /var/www
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: Asia/Jakarta
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
